version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo-app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: todo_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: todo-app

volumes:
  mongo_data: